function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
	AddTextEntry('17m760i', 'BMW M760i')	
	AddTextEntry('180sx', 'Nissan 180SX Type-X')	
	AddTextEntry('370z', 'Nissan 370Z Nismo Z34')
	AddTextEntry('600sel', 'Mercedes-Benz 600 SEL W140')
	AddTextEntry('a8l', 'Audi A8')	
	AddTextEntry('aaq4', 'Audi A4 Quattro ABT 2.0 TFSI')	
	AddTextEntry('ageraone', 'Koenigsegg Agera ONE:1')	
	AddTextEntry('agerars', 'Koenigsegg Agera RS')
	AddTextEntry('ap2', 'Honda S2000')
	AddTextEntry('ast', 'Aston Martin Vanquish')
	AddTextEntry('bbentayga', 'Bentley Bentyaga')
	AddTextEntry('bcgt', 'Bentley Continental GT Cabrio')
	AddTextEntry('bdivo', 'Bugatti Divo')
	AddTextEntry('beetle74', 'Volkswagen Beetle 1974')
	AddTextEntry('ben17', 'Bentley Continental Supersports')
	AddTextEntry('bmci', 'BMW M5 F90')	
	AddTextEntry('bmm', 'Bentley Mulsanne')	
	AddTextEntry('bmwe36', 'BMW Serie 3 E36')	
	AddTextEntry('bmwe38', 'BMW 750i E38')
	AddTextEntry('bmws', 'BMW S1000RR')
	AddTextEntry('s1000', 'BMW S1000RR')
	AddTextEntry('c63coupe', 'Mercedes-Benz C63 AMG Coupe')	
	AddTextEntry('camaro70', 'Chevrolet Camaro Z28 1970')	
	AddTextEntry('camry55', 'Toyota Camry')	
	AddTextEntry('cats', 'Cadillac ATS-V')
	AddTextEntry('cayenne', 'Porsche Cayenne Turbo S')
	AddTextEntry('chevelle1970', 'Chevrolet Chevelle 1970')
	AddTextEntry('chiron17', 'Bugatti Chiron')
	AddTextEntry('cla45sb', 'Mercedes-Benz CLA45 AMG')
	AddTextEntry('cls2015', 'Mercedes-Benz CLS 63 AMG 2015')
	AddTextEntry('cnty', 'Buick Century Limited 1986')
	AddTextEntry('cooperworks', 'MINI Countryman John Cooper Works')
	AddTextEntry('cox2013', 'Volkswagen Beetle')		
	AddTextEntry('cx75', 'Jaguar CX-75 1.6 litros')	
	AddTextEntry('demon', 'Dodge Challenger SRT Demon')	
	AddTextEntry('diplomat83', 'Dodge Diplomat 1983')
	AddTextEntry('elcamino70', 'Chevrolet Camino SS 1970')
	AddTextEntry('evo9', 'Mitsubishi Lancer Evolution IX MR')	
	AddTextEntry('exc530', 'KTM')	
	AddTextEntry('f15078', '1978 Ford F150 XLT')	
	AddTextEntry('f812', 'Ferrari 812')
	AddTextEntry('f82', 'BMW M4 F82')
	AddTextEntry('g65amg', 'Mercedes-Benz G65 AMG')
	AddTextEntry('giulia', 'Alfa Romeo Giulia Quadrifoglio')
	AddTextEntry('gle450', 'Mercedes-Benz GLE 450')
	AddTextEntry('gmt900escalade', 'Cadillac Escalade')
	AddTextEntry('gronos6x6', 'Gronos')
	AddTextEntry('gs350', 'Lexus GS350')
	AddTextEntry('gtr', 'Nissan GT-R')
	AddTextEntry('huayra', 'Pagani Huayra')
	AddTextEntry('i8', 'BMW i8')
	AddTextEntry('kiaspc', 'Kia Sportage')
	AddTextEntry('lada2107', 'VAZ 2107 (Lada Riva)')
	AddTextEntry('laferrari', 'Ferrari La Ferrari')	
	AddTextEntry('ltd85', 'Ford LTD LX 1985')	
	AddTextEntry('lx2018', 'Lexus LX570')	
	AddTextEntry('m2', 'BMW M2')
	AddTextEntry('m5e60', 'BMW M5 E60')
	AddTextEntry('m6f13', 'BMW M6 F13')
	AddTextEntry('mc250', 'Mercedes-Benz C250')
	AddTextEntry('mers63c', 'Mercedes-Benz C63S AMG Cabrio')
	AddTextEntry('mlbrabus', 'Mercedes-Benz ML 2009 Brabus')
	AddTextEntry('p1', 'McLaren P1')
	AddTextEntry('prius', 'Toyota Prius')
	AddTextEntry('pturimso', 'Porsche Panamera Turbo S')
	AddTextEntry('punto', 'Fiat Punto Evo BBS')	
	AddTextEntry('r1', 'Yamaha R1')	
	AddTextEntry('r8ppi', 'Audi R8 V10')
	AddTextEntry('rmodgt63', 'GT 63')
	AddTextEntry('rmodlp770', 'Lamborghini Centenario')	
	AddTextEntry('rmodveneno', 'Lamborghini Veneno')	
	AddTextEntry('rs6', 'Audi RS6 C7')	
	AddTextEntry('rs7', 'Audi RS7 Sportspack')
	AddTextEntry('s63w222', 'Mercedes-Benz S63 AMG W222  Limusina')
	AddTextEntry('skyline', 'Nissan Snkyline GT-R')
	AddTextEntry('srt8', 'Jeep Grand Cherokee SRT8')
	AddTextEntry('supersport', 'Bugatti Veyron Supersport')
	AddTextEntry('supra2', 'Toyota Supra')
	AddTextEntry('tr22', 'Tesla Roadster')
	AddTextEntry('urus', 'Lamborghini Urus')
	AddTextEntry('v250', 'Mercedes-Benz V-250')	
	AddTextEntry('viper', 'Dodge Viper SRT')	
	AddTextEntry('vulcan', 'Aston Martin Vulcan')	
	AddTextEntry('w210', 'Mercedes-Benz E420 W210')
	AddTextEntry('wraith19', 'Rolls-Royce Wraith')
	AddTextEntry('x5m', 'BMW X5M')	
	AddTextEntry('x6m', 'BMW X6M F16')	
	AddTextEntry('xj', 'Jaguar XJ 2010')	
	AddTextEntry('z419', 'BMW Z4 M40')
	AddTextEntry('zl12017', 'Chevrolet Camaro ZL1')	
	AddTextEntry('Camaro', 'Chevrolet Camaro ZL1')	
	AddTextEntry('vxr', 'Toyota Land Cruiser VXR')	
	AddTextEntry('cesc21', 'Cadillac Escalade 2021')	
	AddTextEntry('fxxk', 'Ferrari FXX-K Hybrid')	
	AddTextEntry('fj40', 'Toyota FJ40')
	AddTextEntry('18performante', 'Lamborghini Huracan Performante')
	AddTextEntry('amggtr', 'Mercedes-Benz AMG GTR')
	AddTextEntry('db11', 'Aston Martin DB11')
	AddTextEntry('eb110', 'Bugatti EB110')
	AddTextEntry('f80', 'Ferrari F80')
	AddTextEntry('fxxk', 'Ferrari FXX-K Hybrid')
	AddTextEntry('ie', 'Apollo Intensa Emozione')
	AddTextEntry('laferrari17', 'Ferrari LaFerrari')
	AddTextEntry('lykan', 'W-Motors Lykan Hypersport')
	AddTextEntry('monza', 'Ferrari Monza')
	AddTextEntry('raid', 'Dodge Challenger Raid')
	AddTextEntry('rmodgt63', 'Mercedes-Benz GT63')
	AddTextEntry('spano2016', 'GTA Spano')
	AddTextEntry('terzo', 'Lamborghini Terzo Milenio')
	AddTextEntry('foxct', 'Tesla Cybertruck')
	AddTextEntry('africat', 'Honda Africa EMS')
	AddTextEntry('medvac', 'Ford Interceptor EMS')
	AddTextEntry('ems1', 'Chevrolet Tahoe EMS')
	AddTextEntry('dodgeems', 'Dodge Charger EMS')
	AddTextEntry('psp_bmwgs', 'BMW GS1200 Policia')
	AddTextEntry('690r', 'KTM Duke 390')
	AddTextEntry('biz25', 'Honda C100')
	AddTextEntry('cb500f', 'Honda CBR')
	AddTextEntry('cg160', 'Honda 160')
	AddTextEntry('duker', 'KTM Duke 1290')
	AddTextEntry('gs1', 'BMW R1200')
	AddTextEntry('mt03', 'Yamaha MT03')
	AddTextEntry('mxv450sm', 'Aprilla MXV')
	AddTextEntry('slave', 'Harley Slave')
	AddTextEntry('z1000', 'Kawasaki Z1000')
	AddTextEntry('ellcharg', 'Ford Mach 1 Super')
	AddTextEntry('evovaris', 'Mitsubishi Lancer Evo Tunning')
	AddTextEntry('tritonhpe', 'Mitsubishi Sportero')
	AddTextEntry('911rwb', 'Porsche 911 Le Mans')
	AddTextEntry('992c', 'Porsche 992')
	AddTextEntry('esprit02', 'Lotus Esprit')
	AddTextEntry('f8t', 'Ferrari F8')
	AddTextEntry('radiantvff', 'Monoplaza VFF')
	AddTextEntry('zondar', 'Pagani Zonda R')
	AddTextEntry('asdbx', 'Aston Martin DBX')
	AddTextEntry('dbx', 'Aston Martin DBX')
	AddTextEntry('can', 'UTV CAN')
	AddTextEntry('czr2', 'Chevrolet Colorado')
	AddTextEntry('fjcruiser', 'Toyota FJ')
	AddTextEntry('tahoe', 'Chevrolet Tahoe')
	AddTextEntry('TahoeLTZ', 'Chevrolet Tahoe')
	AddTextEntry('bubbleship', 'Oblivion Bubbleship')
	AddTextEntry('kch53', 'Sikorsky CH-53E')
	AddTextEntry('c8', 'Chevrolet Corvette C8')
	AddTextEntry('mig', 'Ferrari Enzo')
	AddTextEntry('ms1', 'Saleen S1 Mansaug')
	AddTextEntry('dk350z', 'Nissan 350Z Custom')
	AddTextEntry('dm1200', 'Ducati Multistrada')
	AddTextEntry('vulcanpro19', 'Aston Martin Vulcan Pro')
	AddTextEntry('mcst', 'McLaren Speedtail')
	AddTextEntry('blvn', 'Bugatti La Voiture Noire')
	AddTextEntry('qx80', 'Infiniti QX80')
	AddTextEntry('gs1', 'BMW R 1200 GS')
	AddTextEntry('mgt', 'Ford Mustang GT')
	AddTextEntry('raptor2017', 'Ford Velociraptor 6x6')
	AddTextEntry('xxxxx', 'Mercedes-Benz X Class 6x6')
	AddTextEntry('gt17', 'Ford GT')
	AddTextEntry('supraa90', 'Toyota Supra')
	AddTextEntry('488nlargo', 'Ferrari 488N')
	AddTextEntry('jesko2020', 'Koenigsegg Jesko')
	AddTextEntry('ka60', 'Kamov Ka-60')
	AddTextEntry('rmodx6', 'BMW X6')
	AddTextEntry('trhawk', 'Jeep Cherokee Trailhawk')
	AddTextEntry('c7r', 'Chevrolet Corvette C7')
	AddTextEntry('asdbx', 'Aston Martin DBX')
	AddTextEntry('ambucara', 'Caracara EMS')
	AddTextEntry('subn', 'Chevrolet Suburban')
	AddTextEntry('f150', 'Ford F-150')
	AddTextEntry('gsxr', 'Suzuki GSXR1000')
	AddTextEntry('inf', 'Infiniti Q60')
	AddTextEntry('lp670sv', 'Lamborghini Murcielago LP670SV')
	AddTextEntry('unimog', 'Mercedes-Benz Unimog')
	AddTextEntry('onebeast', 'Cadillac The Beast')
	AddTextEntry('patriotc', 'Mammoth Patriot Classic')
	AddTextEntry('tiger2', 'Gaz Tiger')
	AddTextEntry('senna', 'McLaren Senna')
	AddTextEntry('sti', 'Subaru Impreza STI')
	AddTextEntry('semi', 'Tesla Semi')
	AddTextEntry('mvisiongt', 'Mercedes-Benz Vision GT')
	AddTextEntry('jp12', 'Jeep Wrangler 2012 Rubicon')
	AddTextEntry('quadra', 'Cyberpunk 2077 Quadra')
	AddTextEntry('mlnovitec', 'Maserati Levante Novitec')
	AddTextEntry('xt66', 'Yamaha XT 660')
	AddTextEntry('570s', 'McLaren 570S')
	AddTextEntry('atom', 'Ariel Atom')
	AddTextEntry('avalk', 'Aston Martin Valkyrie')
	AddTextEntry('fd', 'Mazda RX-7')
	AddTextEntry('raptor150', 'Ford F-150 Raptor')
	AddTextEntry('rmodmi8lb', 'BMW i8 Tunning')
	AddTextEntry('rmodsian', 'Lamborghini Sián')
	AddTextEntry('trezor', 'Renault Trezor Concept')
	AddTextEntry('wmfenyr', 'W-Motors Fenyr')
	AddTextEntry('rmodp1gtr', 'McLaren P1 GTR')
	AddTextEntry('19gt500', 'Ford Mustang Shelby GT500')
	AddTextEntry('taxi4', 'Alfa Romeo Stelvio Taxi')
	AddTextEntry('taxi3', 'Declasse Taxi')
	AddTextEntry('taxi2', 'Merit Taxi')
	AddTextEntry('taxi', 'Ford Crown Victoria Taxi')
	AddTextEntry('m5t', 'BMW M5 Taxi')
	AddTextEntry('18velar', 'Range Rover Velar')
	AddTextEntry('mi26', 'Mil Mi-26 Halo')
	AddTextEntry('pantera', 'HM-1 Pantera')
	AddTextEntry('bugatticentodieci', 'Bugatti Centodieci')
	AddTextEntry('jesko2020x', 'Koenigsegg Jesko')
	AddTextEntry('tahoe21', 'Chevrolet Tahoe 2021')
	AddTextEntry('yaluxe', 'SuperYate Galaxy')
	AddTextEntry('eifjy', 'Holden Efijy')
	AddTextEntry('etype', 'Jaguar E-Type')
	AddTextEntry('firehawk', 'Helicoptero Firehawk')
	AddTextEntry('lp700', 'Lamborghini Aventador LP-700')
	AddTextEntry('nh2r', 'Kawasaki H2')
	AddTextEntry('dk350z', 'Veilside Nissan 350Z')
	AddTextEntry('dbx', 'Aston Martin DBX')
	AddTextEntry('r50', 'Italdesign Nissan GT-R50')
	AddTextEntry('19xmax', 'Yamaha N-Max')
	AddTextEntry('r1', 'Yamaha R1')
	AddTextEntry('690r', 'KTM Duke 690R')
	AddTextEntry('renault4l', 'Renault 4')
	AddTextEntry('qashqai16', 'Nissan Qashqai')
	AddTextEntry('FK8', 'Honda Civic')
	AddTextEntry('19tundra', 'Toyota Tundra')
	AddTextEntry('mz3c', 'Mazda 3')
	AddTextEntry('elantra07', 'Hyundai Elantra')
	AddTextEntry('rt70', 'Dodge Charger RT70')
	AddTextEntry('bmeclipse95', 'Mitsubishi Eclipse')
	AddTextEntry('cam8tun', 'Toyota Camry')
	AddTextEntry('st', 'Ford Focus ST')
	AddTextEntry('rs62', 'Audi RS6')
	AddTextEntry('zenvo', 'Zenvo ST1')
	AddTextEntry('2016ranger', 'Ford Ranger 2016')
	AddTextEntry('xipodrag', 'Xipo Drag')
	AddTextEntry('tunak', 'Raji Tunak')
	AddTextEntry('bnsgtr99', 'NISSAN SKYLINE GT-R R34 1999')
	AddTextEntry('infernus2se', 'Pegassi Infernus SE Classic')
	AddTextEntry('mcc', 'Peterbilt Mobile Command Center')
	AddTextEntry('pistaspider19', 'Ferrari Pista 488 Spider')
	AddTextEntry('tiffany', 'Chevrolet C10 Classic')

	AddTextEntry('audis8om', 'Audi S8')
	AddTextEntry('bcgt', 'Bentley Continental GT')
	AddTextEntry('ctsv16', 'Cadillac CTS-V')
	AddTextEntry('g65amg', 'Mercedes-Benz G65 AMG')
	AddTextEntry('gl63', 'Mercedes-Benz GL63')
	AddTextEntry('gt17', 'Ford GT')
	AddTextEntry('gtr', 'Nissan GT-R')
	AddTextEntry('zx10r', 'Kawasaki ZX-10R')
	AddTextEntry('vulcan', 'Aston Martin Vulcan')
	AddTextEntry('sq72016', 'Audi SQ7')
	AddTextEntry('rmodpagani', 'Pagani Huayra')
	AddTextEntry('rmodlp770', 'Lamborghini Centenario')
	AddTextEntry('675lt', 'McLaren 675LT')
	AddTextEntry('ast', 'Aston Martin Vanquish')
	AddTextEntry('nissantitan17', 'Nissan Titan Warrior')

	AddTextEntry('rx450h', 'Lexus RX450H')
	AddTextEntry('wald2018', 'Lexus LX570 2018')

	AddTextEntry('4runner', 'Toyota 4Runner')
	AddTextEntry('gemera', 'Koenigsegg Gemera')
	AddTextEntry('lc100', 'Toyota Land Cruiser 100')
	AddTextEntry('mache', 'Mustang Mach E')
	AddTextEntry('tuatara', 'SSC Tuatara')
	AddTextEntry('jtd19tundra', 'Toyota Tundra [PONAL]')
	AddTextEntry('leecounty1', 'Ford Expedition SHERIFF')
	AddTextEntry('bolide', 'Bugatti Bolide')
	AddTextEntry('razor', 'BMW M3 GTR Most Wanted')
	AddTextEntry('lc500', 'Lexus LC 500')
	AddTextEntry('wildtrak', 'Ford Bronco Wildtrak')
	AddTextEntry('it18', 'Italdesign Zerouno')
	AddTextEntry('amggt63', 'Mercedes-AMG GT 63S')
	AddTextEntry('softail1', 'Harley-Davidson Softail')
	AddTextEntry('hvrod', 'Harley-Davidson Fat Boy')
	AddTextEntry('cgt', 'Porsche Carrera GT')

	AddTextEntry('bmwm4', 'BMW M4 Competition')
	AddTextEntry('f8spider', 'Ferrari F8 Spider')
	AddTextEntry('KTMRC39019', 'KTM RC 390')
	AddTextEntry('pts21', 'Porsche 911 Turbo S')
	AddTextEntry('sc18', 'Lamborghini SC18 Alston')
	AddTextEntry('ttrs', 'Audi TT RS')
	AddTextEntry('teslax', 'Tesla Model X')

	AddTextEntry('vsgran', 'Lamborghini V12 Vision GT')

	AddTextEntry('50thpolstang', 'Ford Mustang [EMI]')
	AddTextEntry('polcaptivac140', 'Chevrolet Captiva [EMI]')
	AddTextEntry('hiluxc', 'Chevrolet Captiva [EMI]')
	AddTextEntry('jtdbmwm5', 'BMW M5 [PONAL]')
	AddTextEntry('poltwizy', 'Renault Twizy [PONAL]')
	AddTextEntry('mclarenpd', 'McLaren 650 GT3 [PONAL]')

	AddTextEntry('frr', 'Ford Ranger Raptor')
	AddTextEntry('bmwx7', 'BMW X7')
	AddTextEntry('g63amg6x6', 'Mercedes-AMG G63 6x6')
	AddTextEntry('ram2500', 'Dodge RAM 2500')
	AddTextEntry('rmodx6', 'BMW X6M')
	AddTextEntry('rrghost21', 'Rolls-Royce Ghost SWB')
	AddTextEntry('silv20', 'Chevrolet Silverado')

	AddTextEntry('jtdcyber', 'Tesla Cybertruck [FBI]')

	AddTextEntry('raptor1502', 'Ford Raptor 2017')


end)
